### ISSUE TITLE
Push sent succesfully, the lockscreen wakes up but notification doesnt show up

### ISSUE THREAD

**Issue by evrenios** [grocer/grocer#101]
Hello, this is a huge problem for me. I'm using your great gem and thank you for this (fyi it's faster than houston).

But i have a huge problem.

I'm sending push notification with the same pusher in a foreach loop, and i notice that sometimes push notification delivered succesfully but no notification shows up.

it's like when you received imessage and the message delivered to both your apple computer and iphone and when you read it from your mac the notification on the iphone dissapear. 

This is exactly what is happening. It's really hard to identify this kind of issues so i may be the first reporter but the problem is there.

**Comment by dslysenko** [comment]
Are you setting an alert on the notification 100% of the time? In the iOS app, can you debug in didReceiveRemoteNotification: and check the info dictionary passed to that function to make sure it has an 'alert' key?

**Comment by DmitryRibalka** [comment]
@evrenios I've had this issues for the years, but only today i figured out why it happened.
In a payload sometimes i needed to sent badge: 0
When i removed this, the problem dissapeared

**Comment by stevenharman** [comment]
Hello @evrenios. I'm going to close this Issue due to inactivity. Please re-open it if you are still experiencing the problem and/or have more information to add.

Thank you!
