### ISSUE TITLE
connection drops silently when notification sent to sandbox device token no error, no broken pipe not a single clue

### ISSUE THREAD

**Issue by judgetr** [grocer/grocer#102]
Hello, is there any way to identify this issue?How to eliminate sandbox device token in production environment.

This is a huge problem

**Comment by stevenharman** [comment]
This is related to #95 and #14.

We have an `ErrorResponse` class, but don't currently use it. In #14 you'll find a lengthy discussion and several proposed solutions for not dropping messages and also reading the error response. The most promising would be adding a producer/consumer queue, with a ring buffer to hold sent messages. This would allow us to continue to write at high speeds, but not block while waiting an arbitrary amount of time for an error message from APNS.

None of the original authors currently have available time to undertake the changes, but would be happy to work with any individuals who wish to.

**Comment by judgetr** [comment]
@stevenharman can you tell me what are the tokens that can be considered as invalid token? 

like i already know that sending notification to sandbox token in production is invalid, what else? So another workaround would be for me to eliminiate those
