### ISSUE TITLE
Send notifications using HTTP/2 request

### ISSUE THREAD

**Issue by sunilbg** [grocer/grocer#109]
Apple recently updated their documentation to send push notifications using http/2. The link is https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html

Is there a plan to use this, as we are not sure when Apple is going to deprecate the existing way of sending notifications.

**Comment by stevenharman** [comment]
Hello @sunilbg. Please see Issue #104.
