### ISSUE TITLE
Notification arrives in iphone5, but not in ipad

### ISSUE THREAD

**Issue by llvc** [grocer/grocer#110]
I have created a rails project which send a push notification to Iphone and ipad
```
pusher = Grocer.pusher(certificate: "#{Rails.root}/lib/notification/cer.pem", # required
                       passphrase:  "llvc",                         # optional
                       gateway:     "gateway.sandbox.push.apple.com", # optional
                       port:        2195,                             #optional
                       retries:     3)

        p device_token

        note = Grocer::Notification.new(
          device_token: device_token,
          alert: message,
          sound: 'default',
          badge: 0,
          custom: {
            "linkname": linkname,
            "linkurl": linkurl
          }
 )

pusher.push(note)
```

it works well for iPhone but not for iPad
I want to see the solution.
Thanks.

**Comment by llvc** [comment]
After removing the app from iphone and then installing again it, it also don't worked.

**Comment by stevenharman** [comment]
@llvc If I recall correctly, you'll get a new `device_token` for each install. Did you go through the whole registration flow for each device, and keep the tokens for each install (across each device)? We've seen problems in the past where folks tried using old `device_token`s or tokens from different environments (e.g., sandbox vs prod) and messages fail to send.

**Comment by llvc** [comment]
sure, I update the each new device token and try to send a notification with it. But also fails.

**Comment by llvc** [comment]
I have compiled the ios project and generated pem file by following urls.
https://www.raywenderlich.com/32960/apple-push-notification-services-in-ios-6-tutorial-part-1
It worked perfectly.
