### ISSUE TITLE
Rspec test case for sending ios push notification with Grocer is not working

### ISSUE THREAD

**Issue by himangshubitcanny** [grocer/grocer#111]
I am using grocer gem for sending push notification on IOS device.I have written a model spec I am getting the error

Failure/Error:

```ruby
notification = @server.notifications.pop #=> Timeout::Error: execution expired
```

Please help me out.Thanks in advance.

**Comment by stevenharman** [comment]
Closing this for now. If you have more specific questions, please re-open.
