### ISSUE TITLE
Not getting notifications when badge value changed

### ISSUE THREAD

**Issue by vijirajtp** [grocer/grocer#112]
The documentation tells the badge value as "badge:  42". But whenever the badge value is updated to another value(say, badge: 1), i am not getting the notifications. Is "42" should be default value ? How does the notification count changes if sets the badge value as 42 ?

**Comment by vijirajtp** [comment]
@stevenharman @kbrock @snatchev Anyone please do you know the solution to resolve this issue ?

**Comment by jblac** [comment]
@vijirajtp Not to be the "meanie" here, but how do you expect anyone to help you if you don't show us any of the code you've written?  The documentation can tell you how to do it exactly, if you don't show what you've written how can anyone tell you where you went wrong?

**Comment by vijirajtp** [comment]
pusher = Grocer.pusher(
		  certificate: certificate,      
		  passphrase:  "xxxxxxx",                       
		  gateway:     "gateway.push.apple.com", 
		  port:        2195,                     
		  retries:     3                         
		)

		notification = Grocer::Notification.new(
		  device_token:      self.device_token,
		  alert:             message,
		  badge:             42
		)
Here i have given badge value as '42' here, but when i get the notifications in my device, the notification count is showing as '42'. Anyone please give an idea What does this badge value means ?

**Comment by kbrock** [comment]
Hello @vijirajtp 

I would expect that value to be in `applicationIconBadgeNumber` - which I thought was also the same as the notification count.

I can't seem to find "notification count" on google. They all point to badge number or badge count.

**Comment by stevenharman** [comment]
> Here i have given badge value as '42' here, but when i get the notifications in my device, the notification count is showing as '42'.

That sounds like what's expected, no?

**Comment by stevenharman** [comment]
Hello @vijirajtp. I'm going to close this Issue due to inactivity. Please re-open it if you are still experiencing the problem and/or have more information to add.

Thank you!
