### ISSUE TITLE
Success method undefined on notification

### ISSUE THREAD

**Issue by sai43** [grocer/grocer#117]
Hi,

## NoMethodError (undefined method `success' for #<Grocer::Notification:0xb3c679c0>)

    pusher = Grocer.pusher(
        certificate: pemfile_path,
        passphrase: "passphrase",
        gateway:     "gateway.push.apple.com",
        port:        2195,
        retries:     2
    )

    notification = Grocer::Notification.new(device_token: token,
                                            alert:             message['aps']['alert'],
                                            badge: 1,
                                            sound:             message['aps']['sound'],
                                            content_available: true,
                                            custom: message)
  
    puts pusher.push(notification)    ## it returns 360
    puts "iOS Push -> Success: #{notification.success}, Failed: #{notification.failed}"

**Comment by stevenharman** [comment]
Neither `Grocer::Notification#success` nor `#failed` are methods defined on that object. Hence the error message. Is there a reason you expect them to exist? And what do you expect them to do?

**Comment by sai43** [comment]
From that I want know weather push notification is successfully delivered or not.

**Comment by stevenharman** [comment]
The version of APNS `Grocer` is currently built against has no way of knowing if a notification was successfully delivered to the device or not. The only thing we know is if an error occurred while trying to send the notification to the APNS service. For that, `Grocer` has an [API for accessing the APNS Feedback Service](https://github.com/grocer/grocer#feedback).

A [newer APNS Service](https://github.com/grocer/grocer/issues/104), based on `HTTP/2`, was released by Apple last year. However the current maintainer (me) doesn't have time to change over to that implementation. We are actively [seeking someone to head that work](https://github.com/grocer/grocer#important-note).
