### ISSUE TITLE
SSL_connect returned=1 errno=0 state=unknown state: tlsv1 alert internal error

### ISSUE THREAD

**Issue by federicolucca** [grocer/grocer#119]
HI,

I'm trying to understand what happen.I move the ruby app from a server to another,same ruby same gem same ip. Could be same grocer fix? i try this https://github.com/grocer/grocer/issues/88 but nothing

`App 7031 stderr: /home/ubuntu/.rvm/gems/ruby-2.3.3/gems/grocer-0.7.0/lib/grocer/ssl_connection.rb:43:in `connect'
App 7031 stderr: /home/ubuntu/.rvm/gems/ruby-2.3.3/gems/grocer-0.7.0/lib/grocer/ssl_connection.rb:43:in `connect'
App 7031 stderr: /home/ubuntu/.rvm/gems/ruby-2.3.3/gems/grocer-0.7.0/lib/grocer/connection.rb:29:in `connect'
App 7031 stderr: /home/ubuntu/.rvm/gems/ruby-2.3.3/gems/grocer-0.7.0/lib/grocer/connection.rb:55:in `with_connection'
App 7031 stderr: /home/ubuntu/.rvm/gems/ruby-2.3.3/gems/grocer-0.7.0/lib/grocer/connection.rb:23:in `write'
App 7031 stderr: /home/ubuntu/.rvm/rubies/ruby-2.3.3/lib/ruby/2.3.0/delegate.rb:83:in `method_missing'
App 7031 stderr: /home/ubuntu/.rvm/gems/ruby-2.3.3/gems/grocer-0.7.0/lib/grocer/pusher.rb:8:in `push'`

**Comment by stevenharman** [comment]
@federicolucca Are you sure it's not an incorrect or expired certificate? That often manifests itself as this error.

Also, could it be different versions of OpenSSL on the boxes?

**Comment by federicolucca** [comment]
Hi, thank you

Finally i create a new certificate and everything works.

Federico
