### ISSUE TITLE
Feeding certificate as giant string

### ISSUE THREAD

**Issue by bogardon** [grocer/grocer#62]
Is this possible? I have the entire cert set as an environment variable and would like to jus feed grocer `ENV['APPLE_PUSH_NOTIFICATION_CERT']`.

**Comment by rpavilanis** [comment]
What would this look like then - would I just do this? 

```ruby
StringIO.new(ENV['APPLE_PUSH_NOTIFICATION_CERT'])
```

**Comment by stevenharman** [comment]
@rpavilanis Yep, pretty much!
