### ISSUE TITLE
TLS only starting 2014-10-29

### ISSUE THREAD

**Issue by tbuehlmann** [grocer/grocer#88]
In response to Poodle, Apple only allows TLS connections starting on 2014-10-29. So, no more SSLv3. I couldn't really find something related in the source code, but are we already safe from that?

**Comment by pmatsinopoulos** [comment]
Hi. I am using ruby 2.2.3p173 and I am getting the same error. What am I doing wrong? What do I have to solve this ? Thanks in advance.

**Comment by stevenharman** [comment]
@pmatsinopoulos Which error are you talking about, specifically? Can you provide more information, the exception, and maybe a backtrace?

**Comment by pmatsinopoulos** [comment]
@stevenharman Yes. Sorry I didn't do that in the first place.

Note that I am running on Mac OS X Yosemite.

```
OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A
	from /Users/panayotismatsinopoulos/.rvm/gems/ruby-2.2.3@bookandtable/gems/grocer-0.6.1/lib/grocer/ssl_connection.rb:43:in `connect'
	from /Users/panayotismatsinopoulos/.rvm/gems/ruby-2.2.3@bookandtable/gems/grocer-0.6.1/lib/grocer/ssl_connection.rb:43:in `connect'
	from /Users/panayotismatsinopoulos/.rvm/gems/ruby-2.2.3@bookandtable/gems/grocer-0.6.1/lib/grocer/connection.rb:29:in `connect'
	from /Users/panayotismatsinopoulos/.rvm/gems/ruby-2.2.3@bookandtable/gems/grocer-0.6.1/lib/grocer/connection.rb:55:in `with_connection'
	from /Users/panayotismatsinopoulos/.rvm/gems/ruby-2.2.3@bookandtable/gems/grocer-0.6.1/lib/grocer/connection.rb:23:in `write'
	from /Users/panayotismatsinopoulos/.rvm/gems/ruby-2.2.3@bookandtable/gems/grocer-0.6.1/lib/grocer/pusher.rb:8:in `push'
	from (irb):21
	from /Users/panayotismatsinopoulos/.rvm/gems/ruby-2.2.3@bookandtable/gems/railties-4.2.4/lib/rails/commands/console.rb:110:in `start'
	from /Users/panayotismatsinopoulos/.rvm/gems/ruby-2.2.3@bookandtable/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
	from /Users/panayotismatsinopoulos/.rvm/gems/ruby-2.2.3@bookandtable/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/panayotismatsinopoulos/.rvm/gems/ruby-2.2.3@bookandtable/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/panayotismatsinopoulos/.rvm/gems/ruby-2.2.3@bookandtable/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
```

**Comment by pmatsinopoulos** [comment]
@stevenharman Maybe the problem is that my default params have SSLv23 as default SSL version?

```
{:ssl_version=>"SSLv23", :verify_mode=>1, :ciphers=>"ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-DSS-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA:DHE-DSS-AES128-SHA256:DHE-DSS-AES256-SHA256:DHE-DSS-AES128-SHA:DHE-DSS-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:ECDHE-ECDSA-RC4-SHA:ECDHE-RSA-RC4-SHA:RC4-SHA", :options=>-2097019905} 
```

**Comment by stevenharman** [comment]
Yeah, that's a proble as Apple's Push servers will refuse to connect with that SSL version.

**Comment by pmatsinopoulos** [comment]
@stevenharman Do you know of any way that I can change that?
I have tried this:

```
OpenSSL::SSL::SSLContext::DEFAULT_PARAMS[:ssl_version] = "TLSv1_2"
```
before calling
```
pusher = Grocer.pusher(...
```
but it still gives the same error. I am completely desperate. I am on this the whole day. So, any help would be much appreciated.

**Comment by tilast** [comment]
I have the same issue as @pmatsinopoulos, also I can't fix this.
Or maybe have you @pmatsinopoulos already fixed it?

**Comment by pmatsinopoulos** [comment]
@tilast Yes. I have fixed that. I was not using the correct *.pem file. I was using a *.pem file which was for signing the app and not the one generated especially for provider to communicate as client with the particular app. Does that make sense?

**Comment by tilast** [comment]
@pmatsinopoulos so it was not an issue connected to openssl?

**Comment by pmatsinopoulos** [comment]
@tilast No. It was not. It was my mistake using wrong certificate file.

**Comment by tilast** [comment]
@pmatsinopoulos ok, thanx a lot!

**Comment by gsbabil** [comment]
### More Information

If anyone is still debugging this issue, here's some more information for clarity:

  - Sandbox APNS currently only seems to support:
    - `TLSv1`
    - `TLSv1.1`
    - `TLSv1.2`
  - Production APNS only seems to support: `TLSv1`
  - Both of Sandbox and Production APN servers **no longer support** the following:
    - `SSLv2`
    - `SSLv3`
  - See the screenshots below for clarity
  - Script is here ![https://github.com/gsbabil/check-tls](https://github.com/gsbabil/check-tls)

  - Both Sandbox and Production can't be connected with the default OpenSSL that ships with OS-X **0.9.8zg** (although it seems to support `TLSv1`).
  - One Ubuntu 14.04, the current latest OpenSSL is **1.0.1f**.

Therefore, the only common TLS version that works for both Sandbox and Production APNS is `TLSv1`.

### Test with OpenSSL-0.9.8zg

![screenshot-2](https://cloud.githubusercontent.com/assets/1061108/12008743/a16d87c0-ac06-11e5-911e-71e4d23d168a.png)

### Test with OpenSSL-1.0.2e

![screenshot-1](https://cloud.githubusercontent.com/assets/1061108/12008746/d51d686a-ac06-11e5-9f32-ec122c4b62e2.png)

**Comment by ghazel** [comment]
I am still seeing this issue. ruby 2.1.5p273. grocer 0.6.1.

```
OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A  
        from /home/ec2-user/.rvm/gems/ruby-2.1.5/gems/grocer-0.6.1/lib/grocer/ssl_connection.rb:43:in `connect'  
        from /home/ec2-user/.rvm/gems/ruby-2.1.5/gems/grocer-0.6.1/lib/grocer/ssl_connection.rb:43:in `connect'  
        from /home/ec2-user/.rvm/gems/ruby-2.1.5/gems/grocer-0.6.1/lib/grocer/connection.rb:29:in `connect'  
        from /home/ec2-user/.rvm/gems/ruby-2.1.5/gems/grocer-0.6.1/lib/grocer/connection.rb:55:in `with_connection'  
        from /home/ec2-user/.rvm/gems/ruby-2.1.5/gems/grocer-0.6.1/lib/grocer/connection.rb:23:in `write'  
        from /home/ec2-user/.rvm/gems/ruby-2.1.5/gems/grocer-0.6.1/lib/grocer/pusher.rb:8:in `push'  
```

This is even despite forcing the ssl_version:
```ruby
2.1.5 :003 > puts OpenSSL::SSL::SSLContext::DEFAULT_PARAMS[:ssl_version] 
TLSv1
```

**Comment by gsbabil** [comment]
@ghazel I'm not sure how you've enforced `TLSv1`, but `grocer` in your case still seems to be using `SSLv3`. See this line:

```

**Comment by ghazel** [comment]
I even tried forcing the constructor per https://github.com/grocer/grocer/issues/88#issuecomment-60361838 with `:TLSv1`. It still says `state=SSLv3`.

**Comment by gsbabil** [comment]
@ghazel

**Comment by ghazel** [comment]
Yup, tried that too.

**Comment by ghazel** [comment]
Ah, mine was the same problem as https://github.com/grocer/grocer/issues/88#issuecomment-153413681 -- the APNS push certificate had expired.

**Comment by nextofsearch** [comment]
I am experiencing the same issue in 1.9.3-p448 and the default ssl_version of ruby does not change after upgrading to 1.9.3.-p551. Still SSLv23

`irb(main):004:0> OpenSSL::SSL::SSLContext::DEFAULT_PARAMS[:ssl_version]
=> "SSLv23"`

`SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server session ticket A, `

The weird thing is that I don't get this error all the time. We are processing more than 1M push notifications per day. We only gets this error from time to time. In our cases, expired .pem is not the cause.

**Comment by devmod** [comment]
@nextofsearch I am seeing teh same thing- Today also lots of errors showing up- Let me know if you figure it out

**Comment by Tamiyadd** [comment]
Hi @nextofsearch, suddenly i started to receive same error too. My certificates are not expired and worked well untill 4 days ago. 
Someone figured out the reason because it's happening?

**Comment by nextofsearch** [comment]
@devmod @Tamiyadd It seems that Apple has changed something on their server side. I haven't found any confirmative proof but we are not the only ones experiencing this. I am still looking for the solution but in the mean time, I reduced the push notification job divider from 500 to 100 to minimize the impact.

**Comment by Tamiyadd** [comment]
@nextofsearch i was thinking about something changed in Apple server side too. 
I'm investigating in this way too

**Comment by wilder-misfit** [comment]
@Tamiyadd  I suffer the same problem too. I found developers are talking about the issue on https://forums.developer.apple.com/thread/44677. If there are any updates, please let me know. I will keep tracking the problem too.

**Comment by dsshap** [comment]
I am experiencing this as well, any updates?

**Comment by devmod** [comment]
I thought maybe a couple of nodes going bad- but I captured the failing IPs and it was basically all of them that failed at least once...

**Comment by camdenbrown** [comment]
Hello all, I was having this exact issue also. This post helped us come to a solution. We use our own push notification gem, but it follows the same layout of most push notification gems. The solution ended up being to force 
`OpenSSL::SSL::SSLContext.new :TLSv1`

**Comment by kliffy** [comment]
This issue just went away for me but has popped up again today. setting SSLContext.new to be :TLSv1 does not fix the problem for me.
