### ISSUE TITLE
Unsure of correct usage of feedback connection

### ISSUE THREAD

**Issue by j4zz** [grocer/grocer#90]
I wrote a small script to test the handling of errors using grocer’s feedback mechanism. If I use a production token, it is correctly sent and received.

To test for feedback, I send a notification to a *development* token using the production gateway, and ask the production feedback service for errors. Sadly, I don’t get any feedback from `@feedback.each do |attempt|`:

```ruby
require 'grocer'

class Pusher
  def connect
    @pusher = Grocer.pusher(
      certificate: "apple_push_notification_prod.pem",
      gateway:     "gateway.push.apple.com",
      port:        2195,
      retries:     3
    )
  end

  def send(token)
    notification = Grocer::Notification.new(
      device_token:      token,
      alert:             "We should get feedback",
      badge:             42
    )
    @pusher.push(notification)

    @feedback = Grocer.feedback(
      certificate: "apple_push_notification_prod.pem",
      gateway:     "feedback.push.apple.com",
      port:        2196,
      retries:     3
    )
    @feedback.each do |attempt|
      puts "Device #{attempt.device_token} failed at #{attempt.timestamp}"
    end
  end
end

push_client = Pusher.new
push_client.connect
# Send to a development push notification token (token substituted for this snippet)
push_client.send("517ff994ea1a432a3fb8959017fd31bd052ba2bed3ff7e86dd4f44100c3163ca")
```

Am I using the feedback mechanism incorrectly (grocer 0.6.0)?

**Comment by stevenharman** [comment]
@j4zz, sorry for just getting back to you. I'd missed this issue in my inbox and just discovered it. Sending a _development_ token to the _production_ gateway is an invalid notification and so [APNS will write an error error-response packet](https://developer.apple.com/library/mac/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/CommunicatingWIthAPS.html#//apple_ref/doc/uid/TP40008194-CH101-SW11] on the "push" connection and then close the socket. My bet is that if you read off the push socket after sending a token from a different environment you'll find an error packet, and it will report the token was invalid (status code 8). You can use [`Grocer::ErrorResponse` to verify that](https://github.com/grocer/grocer/blob/master/spec/grocer/error_response_spec.rb).

I'm going to close this issue as I'm nearly certain that's what you're seeing. Please feel free to re-open it if that's not the case. Thanks!
