### ISSUE TITLE
How should I do error handling with grocer?

### ISSUE THREAD

**Issue by larryzhao** [grocer/grocer#91]
I found that if I write a push notification with an old push token ( not an invalid one, just an outdated one. ) to the connection, and the connection is useless. The following push notifications write to the connection are not pushed to the users.

Then I tried with `Grocer::Connection`, after I write the old push token, I can get `\b\b\x00\x00\x00\x00` if I read from the stream. And then if I call `conn.connect` to connect again, the connection can be used for other push notifications, otherwise, whatever notification writes to the connection is not pushed to the user.

What should I do with this? Do I have to read from the stream and handle this or `Grocer` has something which already takes care of it for me?

Thanks a lot.

**Comment by stevenharman** [comment]
This sounds like it might be related to #14. It's a long read, but the gist is that Apple will write an error message and then close the socket. Grocer should recover from the closed socket. BUTH.... there is a period of time between the bad notification being sent and the socket being closed. During that time, any notifications sent will be ignored by Apple.

**Comment by larryzhao** [comment]
Hi, @stevenharman , thanks for the response.

Yes, I found that after I opened this issue. I am now trying out `Rpush`. It runs in a separated process and could reconnect automatically after a wrong token is sent.
