### ISSUE TITLE
Support of action buttons?

### ISSUE THREAD

**Issue by futuretap** [grocer/grocer#94]
Is the `action-loc-key` of the `alert` property supported as well as the rest of the [alert keys](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html#//apple_ref/doc/uid/TP40008194-CH100-SW1)? Couldn't find anything in the code.

**Comment by stevenharman** [comment]
Hello @futuretap.

Yes. The `alert` property can be either a string or a hash. When it's a hash it's passed through to the APNS notification. As per the docs, [you can include the `action-loc-key`](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/ApplePushService.html#//apple_ref/doc/uid/TP40008194-CH100-SW1) which will be used to find a localized string for the button.

I'm going to close this one, but please feel free to re-open if things aren't working as expected.

**Comment by futuretap** [comment]
Thanks, I already figured out that I can just replace the string with a dictionary. For whatever reason it doesn't work yet, the action button isn't shown. But that's probably an issue on the iOS side of things.
