### ISSUE TITLE
How to set Priority?

### ISSUE THREAD

**Issue by devmod** [grocer/grocer#98]
Hello,

Is there a way to set priority: 10 ?

Thanks

**Comment by stevenharman** [comment]
Hello @devmod,

We currently still send ["Legacy" Enhanced notifications](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/LegacyFormat.html). They default to a priority of 10, so there's nothing you need to do. We probably need to move to the [new notification format](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/CommunicatingWIthAPS.html#//apple_ref/doc/uid/TP40008194-CH101-SW4).

**Comment by devmod** [comment]
Got it. Thanks!
